config/routes.rb
Rails.application.routes.draw do
 
  authenticate :user do
    root to: 'dashboards#index', as: :authenticated_root
    get 'dashboard', to: 'dashboards#index', as: 'dashboard'
    get  'report', to: 'reports#index', as: 'report'
    post 'search', to: 'dashboards#search', defaults: { format: :js }
    resources :patients, only: [ :create, :edit, :update ] do
      resources :calls, only: [ :create ]
      resources :notes, only: [ :create, :update ]
      resources :pledges, only: [ :create, :update ]
    end
    patch 'users/:user_id/add_patient/:id', to: 'users#add_patient', as: 'add_patient', defaults: { format: :js }
    patch 'users/:user_id/remove_patient/:id', to: 'users#remove_patient', as: 'remove_patient', defaults: { format: :js }
    patch 'users/reorder_call_list', to: 'users#reorder_call_list', as: 'reorder_call_list', defaults: { format: :js }
  end
  root :to => redirect('/users/sign_in')
  devise_for :users, skip: [:registrations]
  as :user do
    get '/users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put '/users' => 'devise/registrations#update', as: 'registration'
  end
end

app/controllers/dashboards_controller.rb
# Basically just search and the home view
class DashboardsController < ApplicationController
  def index
    @urgent_patients = Patient.urgent_patients
  end

  def search
    @results = Patient.search params[:search]

    @patient = Patient.new
    @today = Time.zone.today.to_date
    @phone = searched_for_phone?(params[:search]) ? params[:search] : ''
    @name = searched_for_name?(params[:search]) ? params[:search] : ''

    respond_to { |format| format.js }
  end

  private

  def searched_for_phone?(query)
    !/[a-z]/i.match query
  end

  def searched_for_name?(query)
    /[a-z]/i.match query
  end
end

app/helpers/dashboards_helper.rb
# Convenience methods consumed in the dashboards controller index view
module DashboardsHelper
  def week_range(date: DateTime.now.in_time_zone, start_day: :monday)
    week_start = date.beginning_of_week start_day
    week_end = date.end_of_week start_day
    week_start_string = week_start.strftime('%B %-d')
    week_end_string = if week_start.month == week_end.month
                        week_end.strftime('%-d')
                      else
                        week_end.strftime('%B %-d')
                      end
    "#{week_start_string} - #{week_end_string}"
  end

  def voicemail_options
    enum_text = { not_specified: 'No instructions; no ID VM',
                  no: 'Do not leave a voicemail',
                  yes: 'Voicemail OK' }
    vm_options = Patient::VOICEMAIL_PREFERENCE

    vm_options.map { |option| [enum_text[option], option] }
  end
end

app/views/dashboards/_overview.html.erb
<div id="overview" class="margin-bottom">
  <h1 class="border-bottom title">Week of <%= week_range %></h1>
  <!--
  <div class="progress">
    <div class="progress-bar progress-bar-success" style="width: 35%">
      <span class="sr-only">35% Complete (success)</span>
    </div>
    <div class="progress-bar progress-bar-warning progress-bar-striped" style="width: 20%">
      <span class="sr-only">20% Complete (warning)</span>
    </div>
    <div class="progress-bar progress-bar-danger" style="width: 10%">
      <span class="sr-only">10% Complete (danger)</span>
    </div>
  </div>
  -->
</div>

app/views/dashboards/_search_form.html.erb
<div id="search_form" class="margin-bottom">
  <h1 class="border-bottom title">Build your call list</h1>

  <!-- TODO change submit tag to a search glyphicon -->
  <%= bootstrap_form_tag url: '/search', remote: true, layout: :inline do |p| %>
    <%= p.text_field :search, placeholder: 'Name (Susan Smith) or Phone (555-555-5555)', hide_label: true, class: 'search_form_input' %>
    <%= p.submit 'Search', class: 'btn btn-primary' %>
  <% end %>

  <div id="search_results_shell"></div>
</div>

app/views/dashboards/_table_content.html.erb
<!-- locals: title, table_type (for div id and tbody div id), pregnancies, sortable -->

<div id="<%= table_type %>" class="margin-bottom">
  <h1 class="border-bottom title"><%= title %></h1>
  <table class="table border-side">
    <thead>
      <tr>
        <% if local_assigns[:sortable] %>
          <th><!-- handle --></th>
        <% end %>
        <th>Phone</th>
        <th>Name</th>
        <th>LMP</th>
        <th>Status</th>
        <th>Notes</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody id="<%= table_type %>_content">
      <% patients.each do |patient| %>
        <tr class="pregnancy-data" id="<%= patient.id %>">
          <% if local_assigns[:sortable] %>
            <td class="handle"><span class="glyphicon glyphicon-move"></span></td>
          <% end %>
          <td><%= patient.primary_phone_display %></td>
          <td><%= link_to patient.name, edit_patient_path(patient) %></td>
          <td><%= patient.pregnancy.last_menstrual_period_display_short %></td>
          <td><%= patient.status %></td>
          <td><%= patient.most_recent_note_display_text %> <%= plus_sign_glyphicon(patient.most_recent_note) %></td>

          <% if table_type == 'completed_calls' || table_type == 'urgent_patients' %>
            <td class="blank-td"></td>
          <% else %>
            <% if current_user.patients.include?(patient) %>
              <td><%= link_to "Remove", remove_patient_path(current_user, patient), method: :patch, remote: true %></td>
            <% else %>
              <td><%= link_to "Add", add_patient_path(current_user, patient), method: :patch, remote: true %></td>
            <% end %>
          <% end %>

          <td><%= link_to "<span class='glyphicon glyphicon-earphone' aria-hidden='true'></span><span class='sr-only'>Call</span>".html_safe, "#call-#{patient.primary_phone_display}", data: {toggle: "modal"} %></td>

          <%= render partial: 'calls/new_call', locals: {patient: patient} %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboards/index.html.erb
<script>
  $(function () {
    $('[data-toggle="popover"]').popover()
  })
</script>

<div class="container">
  <div class="col-sm-12">
    <%= render partial: 'dashboards/overview' %>
    <%= render partial: 'dashboards/search_form' %>
    <%= render partial: 'dashboards/table_content', locals: { title: 'Your call list', table_type: 'call_list', patients: current_user.ordered_patients, sortable: true } %>
    <%= render partial: 'dashboards/table_content', locals: { title: 'Your completed calls', table_type: 'completed_calls', patients: current_user.recently_called_patients } %>
    <%= render partial: 'dashboards/table_content', locals: { title: 'Urgent cases', table_type: 'urgent_patients', patients: @urgent_patients } %>
  </div>
</div>

app/views/dashboards/search.js.erb
$('#search_results_shell').empty();
<% if @results.blank? %>
  $("#search_results_shell").append("<%= escape_javascript(render partial: 'patients/new_patient', locals: { patient: @patient, name: @name, phone: @phone, today: @today }) %>");
<% else %>
  $("#search_results_shell").append("<%= escape_javascript(render partial: 'dashboards/table_content', locals: { title: 'Search results', table_type: 'search_results', patients: @results } ) %>");
<% end %>