config/routes.rb
Rails.application.routes.draw do
 
  authenticate :user do
    root to: 'dashboards#index', as: :authenticated_root
    get 'dashboard', to: 'dashboards#index', as: 'dashboard'
    get  'report', to: 'reports#index', as: 'report'
    post 'search', to: 'dashboards#search', defaults: { format: :js }
    resources :patients, only: [ :create, :edit, :update ] do
      resources :calls, only: [ :create ]
      resources :notes, only: [ :create, :update ]
      resources :pledges, only: [ :create, :update ]
    end
    patch 'users/:user_id/add_patient/:id', to: 'users#add_patient', as: 'add_patient', defaults: { format: :js }
    patch 'users/:user_id/remove_patient/:id', to: 'users#remove_patient', as: 'remove_patient', defaults: { format: :js }
    patch 'users/reorder_call_list', to: 'users#reorder_call_list', as: 'reorder_call_list', defaults: { format: :js }
  end
  root :to => redirect('/users/sign_in')
  devise_for :users, skip: [:registrations]
  as :user do
    get '/users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put '/users' => 'devise/registrations#update', as: 'registration'
  end
end

app/views/layouts/_footer.html.erb
<div class="container">
	<hr class="hr_gradient">
	<div class="row">
		<div class="col-sm-12 text-center">
			<small>Please send feedback or ideas for this case management app to <a href="mailto:DCAF.CMapp@gmail.com">DCAF.CMapp@gmail.com</a></small>
		</div>
	</div><!-- end row -->
</div><!-- end container -->
	  
<div id="app_footer" class="container text-center margin-bottom-sm">
	<a href="http://dcabortionfund.org/">DC Abortion Fund</a> -- <a href="tel:202-452-7464"><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> 202-452-7464</a><br>
	<a href="https://prochoice.org/">National Abortion Federation</a> -- <a href="tel:800-772-9100"><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> 800-772-9100</a><br>
	<a href="http://onlinefaxes.com">onlinefaxes.com</a>
</div><!-- end container -->

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if name != 'timedout' && msg.length > 0 %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'DCAF Case Manager', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <%= render 'layouts/navigation_links' %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if !user_signed_in? %>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
  <% else %>
    <% unless current_page?(authenticated_root_url) %>
      <li><%= link_to 'Dashboard', authenticated_root_path %></li>
    <% end %>
    <li><%= link_to current_user.name, edit_user_registration_path %></li>
    <li><%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "DCAF Case Management System" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "DCAF" %>">
    <meta name='ROBOTS' content='NOINDEX, NOFOLLOW'>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if current_user.present? %>
      <header>
        <%= render 'layouts/navigation' %>
      </header>
    <% end %>
    <main role="main">
      <div class="container">
        <%= render 'layouts/messages' %>

        <br>
        <%= yield %>
      </div>
    </main>
    <% if current_user.present? %>
      <footer>
        <%= render 'layouts/footer' %>
      </footer>
    <% end %>
  </body>
</html>